# version: 2.1
# orbs:
#   node: circleci/node@1.1
# jobs:
#   build:
#     executor:
#       name: node/default
#       tag: '10.4'
#     steps:
#       - checkout
#       - node/with-cache:
#           steps:
#             - run: npm install
#       - run: npm run test
version: '2.1'
orbs:
  node: circleci/node@4.7
jobs:
  test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test